### ISSUE TITLE
Move to JuliaCI and register?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/LocalCoverage.jl#12]
@tpapp What do you think about:
1. Moving this package to e.g. the JuliaCI organization
2. Registering it in the General registry

**Comment by tpapp** [comment]
Fine with me. I have little bandwidth for maintenance but added @ExpandingMan as a maintainer. Would you be interested in helping out? Then I can add you too.

**Comment by ExpandingMan** [comment]
Yes, it would be nice to move this to JuliaCI.  Not really sure what's involved.  I am a maintainer, but don't seem to have the github "settings" button, so if we have to do it from our end, I think @tpapp still needs to do it.  Also not sure how to change the URL in the registry.  If you can give us steps here, I would be glad to help out if I can.

**Comment by tpapp** [comment]
I am happy to do this but I am unsure about the steps too.

**Comment by tpapp** [comment]
I looked at the Github docs and I think that giving me access to JuliaCI would allow me to make the transfer. This also makes sense, since I guess that otherwise I would have no write access to the repo afterwards.

If you do this, please also grant @ExpandingMan the same rights.

**Comment by DilumAluthge** [comment]
@tpapp Try to transfer now. You may need to first accept the invitation to join JuliaCI.

**Comment by DilumAluthge** [comment]
The transfer is complete. @tpapp and @ExpandingMan you both should have admin access.
