### ISSUE TITLE
Proposal : Replace python dependency for lcov -> xml conversion

### ISSUE THREAD

**Issue by BambOoxX** [JuliaCI/LocalCoverage.jl#41]
Hi folks, I was just in need of an LCOV to cobertura XML converter and I was not happy with requiring a python package there, so I wrote an naive equivalent of `lcov_cobertura.py`. If you want I can open a PR to merge it here so that you can drop the python dependency. 

The only dependencies are Dates, OrderedCollections, EzXML. 

I would still need a bit of work but it works on one of my packages except for the DOCTYPE node (I opened a question on the discourse about that https://discourse.julialang.org/t/lcov-cobertura-format-conversion/93200

**Comment by tpapp** [comment]
That would be great, please go ahead with a PR.

**Comment by BambOoxX** [comment]
I'll be wokring on it today, I'll probabnly push it this evening

**Comment by BambOoxX** [comment]
I'll close this for now though it could be a bit more polished before dropping the python part.
